title: PAT Solution in C
author: LuXu
email: oliver_lew@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  浙江大学编程能力测试(PAT)C语言题解说明
baseurl: "/PAT" # the subpath of your site, e.g. /blog
url: "http://oliverlew.github.io/PAT/" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  oliverlew
rss: rss

plugins:
  - jekyll-feed

# Build settings
github: [metadata]
encoding: UTF-8
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
future: true
show_excerpts: false

theme: minima

header_pages:
  - Basic.md
  - Advanced.md
  - Top.md
  - about.md

exclude: [PATAdvanced/, PATBasic/, Gemfile, Gemfile.lock, source, README.md]

# collections
collections:
  articles:
    output: true

# Google Analytics
google_analytics: UA-118900116-1

# Gitalk
gitalk:
  # NOTE: id configuration is in _includes/gitalk.html
  enabled: true
  clientID: '7bf7cca48411ad47d5c3'
  clientSecret: '9b1d5d7c3aa64fe4f5e4c8e71ea597e63f6e83b9'
  repo: 'oliverlew.github.io'
  owner: 'OliverLew'
  admin: 'OliverLew'
  distractionFreeMode: false
  lables: ['Gitalk', 'PAT solutions in C']
  pagerDirection: 'first'
  createIssueManually: true

# vim:tabstop=2:softtabstop=2:shiftwidth=2
