title: PAT Solution in C
email: oliver_lew@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  浙江大学编程能力测试(PAT)C语言题解说明
baseurl: "/PAT" # the subpath of your site, e.g. /blog
url: "http://oliverlew.github.io/PAT/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  oliverlew
rss: rss

plugins:
  - jekyll-feed

# Build settings
github: [metadata]
encoding: UTF-8
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
future: true
#jailed: false
gfm_quirks: paragraph_end
theme: minima
exclude: [PATAdvanced/, PATBasic/, Gemfile, Gemfile.lock, source]

# collections
collections:
  articles:
    output: true
    permalink: /:path:output_ext

# vim:tabstop=2:softtabstop=2:shiftwidth=2
