title: PAT Solution in C
email: oliver_lew@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  浙江大学编程能力测试(PAT)C语言题解说明
baseurl: "/PAT" # the subpath of your site, e.g. /blog
url: "http://oliverlew.github.io/PAT/" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  oliverlew
rss: rss

plugins:
  - jekyll-feed

# Build settings
github: [metadata]
encoding: UTF-8
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
future: true
show_excerpts: false

theme: minima
#remote-theme: benbalter/retlab
header_pages:
  - about.md

exclude: [PATAdvanced/, PATBasic/, Gemfile, Gemfile.lock, source, README.md]

# collections
collections_dir: _articles
collections:
  Advanced:
    output: true
    permalink: /:collection/:path:output_ext
  Basic:
    output: true
    permalink: /:collection/:path:output_ext
  Top:
    output: true
    permalink: /:collection/:path:output_ext

# vim:tabstop=2:softtabstop=2:shiftwidth=2
