title: PAT Solution
email: oliver_lew@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  浙江大学编程能力测试(PAT)题解说明
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://oliverlew.github.io/PAT/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  oliverlew
# Build settings
github: [metadata]
encoding: UTF-8
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
theme: minima
exclude: [html/, md/, analysis/]
